# Generated by Django 6.0 on 2025-12-19 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0003_course_module_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='module',
        ),
        migrations.AddField(
            model_name='topic',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='elearning.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('video', 'Video'), ('image', 'Image'), ('animation', 'Animation'), ('document', 'Word File')], max_length=20)),
                ('file_url', models.URLField()),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='elearning.topic')),
            ],
        ),
        migrations.DeleteModel(
            name='Module',
        ),
    ]
