# Generated by Django 6.0 on 2025-12-19 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0004_remove_topic_module_topic_course_topic_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='file_url',
        ),
        migrations.AddField(
            model_name='media',
            name='file',
            field=models.FileField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
    ]
