# Generated by Django 5.2.9 on 2026-02-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0009_course_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='questions',
            name='que_type',
            field=models.CharField(choices=[('mcq', 'Mcq'), ('pair', 'Pair'), ('imgage', 'Image')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questions',
            name='correct_option',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option_a',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option_b',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option_c',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option_d',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='selected_option',
            field=models.CharField(max_length=500),
        ),
    ]
