# Generated by Django 5.2.9 on 2026-02-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0010_questions_file_questions_que_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='ans_count',
            field=models.IntegerField(default=0),
        ),
    ]
