# Generated by Django 5.2.9 on 2026-03-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0011_questions_ans_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_verification',
            field=models.BooleanField(default=False),
        ),
    ]
