# Generated by Django 5.2.9 on 2026-04-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0012_user_otp_verification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['order_by']},
        ),
        migrations.AddField(
            model_name='topic',
            name='order_by',
            field=models.IntegerField(default=0),
        ),
    ]
