# Generated by Django 5.2.9 on 2026-04-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0013_alter_topic_options_topic_order_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['order_by']},
        ),
        migrations.AddField(
            model_name='course',
            name='order_by',
            field=models.IntegerField(default=0),
        ),
    ]
