# Generated by Django 5.2.9 on 2026-04-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0014_alter_course_options_course_order_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourseprogress',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='usercourseprogress',
            constraint=models.UniqueConstraint(fields=('user', 'course'), name='unique_user_course_progress'),
        ),
    ]
