# Generated by Django 5.2.9 on 2026-04-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0015_usercourseprogress_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_login',
            field=models.BooleanField(default=False),
        ),
    ]
